// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jofxbzahahisqctngypi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvZnhiemFoYWhpc3FjdG5neXBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MjMyMjUsImV4cCI6MjA2ODA5OTIyNX0.mpZlqNVY3LNMm4VUgda3HFZ1svSHZMIHcfwCDZ_djmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});